# Automated training pipeline for the TDASS Oracle's dual-branch neural architecture.
"""
# This script orchestrates the training of both the Action Predictor (LSTM) and the Intent Classifier.
train_oracle.py — B5: Oracle Training Pipeline
================================================
# It processes a synthetic tactical dataset to teach the model how to forecast enemy movements and high-level strategies.
Trains both the LSTM action predictor and the intent classifier
on the enhanced synthetic dataset.

# Key machine learning components implemented in this pipeline:
Features:
# Prevents over-representation of specific scenarios by ensuring the distribution of classes is equal in both sets.
  - Train/val split with stratified sampling
# Visual diagnostic tools to monitor for overfitting or divergence during the gradient descent process.
  - Loss curves saved as matplotlib plots
# Automates the preservation of the model state based on validation performance, ensuring we never lose the 'best' version.
  - Model checkpointing (best val accuracy)
# Comprehensive metrics (Precision, Recall, F1-Score) to evaluate the model's reliability across different action types.
  - Classification report on validation set
# Real-time feedback loop for the engineer to monitor epoch-by-epoch training speed and loss reduction.
  - Progress bars via tqdm (falls back to print)
"""

# Import standard OS interface to handle file paths and directory creation.
import os
# Import sys to modify the python path, allowing us to import sibling modules in the project hierarchy.
import sys
# Import time for performance benchmarking and epoch duration tracking.
import time
# Import json to export training metadata and final accuracy scores in a machine-readable format.
import json
# Import numpy for data manipulation and randomized index generation.
import numpy as np
# The core machine learning framework for building and training neural networks.
import torch
# Provides the base building blocks for neural network layers and training objectives.
import torch.nn as nn
# Contains optimization algorithms like Adam and SGD.
import torch.optim as optim
# Import metrics for high-fidelity evaluation of the classification performance.
from sklearn.metrics import classification_report, confusion_matrix

# Injects the project root into the system path so that 'oracle' and other folders are recognizable as packages.
# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Import data utilities: get_dataloaders handles the windowed sequence generation and batching.
from oracle.data_loader import (
    get_dataloaders, POSTURE_CLASSES, ACTION_CLASSES, FEATURE_COLS
)
# Load the architecture definitions: B2 handles micro-actions, B3 handles macro-intent.
from oracle.lstm_predictor import LSTMPredictor
from oracle.intent_classifier import IntentClassifier

# Attempt to load TQDM for visual progress bars; use a simple pass-through if the library isn't installed.
try:
    from tqdm import tqdm
except ImportError:
    def tqdm(iterable, **kwargs):
        return iterable


# ──────────────────────────────────────────────
# Training Configuration: The Hyperparameter Grid.
# ──────────────────────────────────────────────

# Centralized configuration dictionary (Hyperparameters) that controls the "learning" behavior of the network.
DEFAULT_CONFIG = {
    # File path pointing to the ground-truth synthetic data generated by the tactical simulation.
    "csv_path":      "Element_Logic/Synthetic_dataset/battle_data.csv",
    # The length of the temporal window (history) the model looks at to make a prediction.
    "window_size":   10,
    # The number of data samples processed before the model updates its internal weights.
    "batch_size":    256,
    # 20% of data is held out to test if the model has actually 'learned' or just 'memorized' the training data.
    "val_split":     0.2,
    # Number of complete passes through the entire dataset.
    "epochs":        30,
    # The step size for gradient descent; too high causes divergence, too low makes training slow.
    "lr":            1e-3,
    # L2 regularization factor that penalizes large weights, helping prevent overfitting.
    "weight_decay":  1e-5,
    # Width of the hidden representations in the LSTM and Linear layers.
    "hidden_size":   128,
    # Stacking two LSTM layers allows the network to capture complex hierarchical temporal patterns.
    "num_layers":    2,
    # Probability of zeroing out neurons during training to ensure the model doesn't rely on specific data noise.
    "dropout":       0.3,
    # Destination folder for the best-performing model weights (.pt files).
    "checkpoint_dir": "oracle/checkpoints",
    # Automatically selects high-performance NVIDIA GPU (CUDA) if available, otherwise falls back to CPU.
    "device":        "cuda" if torch.cuda.is_available() else "cpu",
}

# Mapping of integer indices to human-readable action names for the final classification report.
ACTION_NAMES = ["Stay", "Up", "Down", "Left", "Right", "Ranged"]


# ──────────────────────────────────────────────
# Core Training Logic: The Optimization Loop.
# ──────────────────────────────────────────────

# Executional logic for training the Action Predictor (Branch B2) for one epoch.
def train_epoch(model, loader, criterion, optimizer, device):
    """Executes a single training pass. Returns average loss and accuracy for the epoch."""
    # Put the model into 'Training Mode' to enable dropout and batch normalization layers.
    model.train()
    # Track the cumulative loss and prediction accuracy across all batches in this epoch.
    total_loss, correct, total = 0.0, 0, 0

    # Iteratively pull mini-batches from the data loader.
    for X_batch, y_batch, _ in loader:
        # Transfer the input tensors and labels to the designated training hardware (CPU/GPU).
        X_batch = X_batch.to(device)
        y_batch = y_batch.to(device)

        # Step 1: Clear the internal gradients from the previous batch to prevent accumulation.
        optimizer.zero_grad()
        # Step 2: Forward Pass - Run the tactical data through the LSTM to get prediction logits.
        logits = model(X_batch)
        # Step 3: Compute Loss - Measure the mathematical 'distance' between predictions and ground truth.
        loss = criterion(logits, y_batch)
        # Step 4: Backward Pass - Calculate the gradient of the loss with respect to every weight in the network.
        loss.backward()
        # TECHNIQUE: Gradient Clipping - Rescales gradients if they exceed a certain threshold to prevent 'Exploding Gradients'.
        nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        # Step 5: Update Weights - Adjust the neural network's parameters according to the calculated gradients.
        optimizer.step()

        # Update running tallies for reporting.
        total_loss += loss.item() * X_batch.size(0)
        # Select the class index with the highest probability as our prediction.
        preds = torch.argmax(logits, dim=-1)
        # Increment 'correct' if the predicted action ID matches the true action ID.
        correct += (preds == y_batch).sum().item()
        # Count total samples processed.
        total += X_batch.size(0)

    # Return the normalized average loss and accuracy percentage.
    return total_loss / total, correct / total


# Specialized training function for the Posture/Intent Branch (B3).
def train_epoch_posture(model, loader, criterion, optimizer, device):
    """Executes a single training pass for the intent classifier (strategic postures)."""
    # Active learning mode.
    model.train()
    # Stats buffers.
    total_loss, correct, total = 0.0, 0, 0

    # For Branch B3, we use the THIRD item in the batch tuple (the posture label).
    for X_batch, _, y_batch in loader:
        # Push to targeted compute device.
        X_batch = X_batch.to(device)
        y_batch = y_batch.to(device)

        # Standard optimization step.
        optimizer.zero_grad()
        logits = model(X_batch)
        loss = criterion(logits, y_batch)
        loss.backward()
        # Ensures that large updates don't destabilize the hidden states of our bidirectional LSTM.
        nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        # Record metrics.
        total_loss += loss.item() * X_batch.size(0)
        preds = torch.argmax(logits, dim=-1)
        correct += (preds == y_batch).sum().item()
        total += X_batch.size(0)

    # Return reporting metrics.
    return total_loss / total, correct / total


# Post-training evaluation function to test the model's accuracy on unseen validation data.
@torch.no_grad() # Disables gradient calculations to save memory and increase speed during evaluation.
def evaluate(model, loader, criterion, device, target_idx=1):
    """Calculates model metrics on the hold-out validation set."""
    # Put the model into 'Evaluation Mode' (disables dropout for stable predictions).
    model.eval()
    # Stats buffers.
    total_loss, correct, total = 0.0, 0, 0
    # Containers to store every true label and prediction for final reporting (Confusion Matrix/F1).
    all_preds, all_labels = [], []

    # Iterate batches without updating weights.
    for batch in loader:
        # Load features and select the target label (1 for Action, 2 for Posture).
        X_batch = batch[0].to(device)
        y_batch = batch[target_idx].to(device)

        # Single forward pass to get current intelligence outputs.
        logits = model(X_batch)
        loss = criterion(logits, y_batch)

        # Update accuracy and loss counters.
        total_loss += loss.item() * X_batch.size(0)
        preds = torch.argmax(logits, dim=-1)
        correct += (preds == y_batch).sum().item()
        total += X_batch.size(0)

        # Store results for the final Scikit-Learn classification report.
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(y_batch.cpu().numpy())

    # Calculate final averages.
    avg_loss = total_loss / total
    accuracy = correct / total
    # Return the metrics alongside the raw arrays for detailed statistical analysis.
    return avg_loss, accuracy, np.array(all_preds), np.array(all_labels)


# ──────────────────────────────────────────────
# Pipeline Orchestration: The Master Function.
# ──────────────────────────────────────────────

# Main entry point for the training phase of the TDASS project.
def train_oracle(config=None):
    """Orchestrates the parallel training of the Action and Intent subsystems."""
    # Combine standard settings with any custom trial parameters provided.
    cfg = {**DEFAULT_CONFIG, **(config or {})}

    # Ensure the architecture's checkpoint folder exists on the drive.
    os.makedirs(cfg["checkpoint_dir"], exist_ok=True)

    # Branding header for the console session.
    print("╔═══════════════════════════════════════════════════╗")
    print("║  TDSS Oracle — Training Pipeline                 ║")
    print(f"║  Device: {cfg['device']:<42}║")
    print("╚═══════════════════════════════════════════════════╝")

    # Step 1: Preprocessing – Convert the simulated world logs into windowed tensors.
    print("\n📊 Loading and preprocessing data...")
    train_loader, val_loader, posture_encoder, num_features = get_dataloaders(
        cfg["csv_path"], cfg["window_size"], cfg["batch_size"], cfg["val_split"]
    )

    # ═══════════════════════════════════════════
    # Sub-Phase B2: Action Predictor Training
    # ═══════════════════════════════════════════
    print("\n" + "=" * 55)
    print("  Phase B2: LSTM Action Predictor")
    print("=" * 55)

    # Initialize the Action Model architecture with our feature count and configuration.
    action_model = LSTMPredictor(
        input_size=num_features,
        hidden_size=cfg["hidden_size"],
        num_layers=cfg["num_layers"],
        num_classes=ACTION_CLASSES,
        dropout=cfg["dropout"],
    ).to(cfg["device"])

    # Report the complexity (parameter count) of the brain we are building.
    print(f"  Parameters: {sum(p.numel() for p in action_model.parameters()):,}")

    # Use CrossEntropyLoss which is standard for multi-class classification tasks.
    action_criterion = nn.CrossEntropyLoss()
    # Use the Adam optimizer—a state-of-the-art algorithm that implements adaptive momentum.
    action_optimizer = optim.Adam(
        action_model.parameters(), lr=cfg["lr"], weight_decay=cfg["weight_decay"]
    )
    # TECHNIQUE: Learning Rate Scheduler - Reduces the 'speed' of learning if the model stops improving.
    # This acts like a 'fine-tuning' pass at the end of training.
    action_scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        action_optimizer, mode="min", factor=0.5, patience=3
    )

    # Variables for tracking the 'Champion' model state.
    best_action_acc = 0.0
    action_history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": []}

    # Iterate through the number of 'Epochs' (complete dataset passes).
    for epoch in range(1, cfg["epochs"] + 1):
        t0 = time.time()
        # 1. Run the optimized training pass for this epoch.
        train_loss, train_acc = train_epoch(
            action_model, train_loader, action_criterion,
            action_optimizer, cfg["device"]
        )
        # 2. Immediately test against the validation set to check for generalization.
        val_loss, val_acc, _, _ = evaluate(
            action_model, val_loader, action_criterion, cfg["device"], target_idx=1
        )
        # 3. Inform the scheduler of the current performance so it can adjust the LR.
        action_scheduler.step(val_loss)
        dt = time.time() - t0

        # Store logs for the final training curve plots.
        action_history["train_loss"].append(train_loss)
        action_history["val_loss"].append(val_loss)
        action_history["train_acc"].append(train_acc)
        action_history["val_acc"].append(val_acc)

        # Highlight if this epoch achieved a new 'High Score' in validation accuracy.
        marker = " ★" if val_acc > best_action_acc else ""
        print(f"  Epoch {epoch:>2}/{cfg['epochs']}  "
              f"Loss: {train_loss:.4f}/{val_loss:.4f}  "
              f"Acc: {train_acc:.3f}/{val_acc:.3f}  "
              f"[{dt:.1f}s]{marker}")

        # If this is the best model so far, save it to the drive.
        if val_acc > best_action_acc:
            best_action_acc = val_acc
            torch.save(action_model.state_dict(),
                       os.path.join(cfg["checkpoint_dir"], "action_predictor_best.pt"))

    # Final detailed analysis of where the model is succeeding or failing (Precision/Recall).
    _, _, a_preds, a_labels = evaluate(
        action_model, val_loader, action_criterion, cfg["device"], target_idx=1
    )
    print(f"\n  Best Action Accuracy: {best_action_acc:.4f}")
    print("\n  Action Classification Report:")
    print(classification_report(a_labels, a_preds, target_names=ACTION_NAMES,
                                labels=range(ACTION_CLASSES), zero_division=0))

    # ═══════════════════════════════════════════
    # Sub-Phase B3: Intent Classifier Training
    # ═══════════════════════════════════════════
    print("\n" + "=" * 55)
    print("  Phase B3: Intent Classifier (Posture)")
    print("=" * 55)

    # Initialize the Intent architecture with Mean-Pooling logic enabled internally.
    intent_model = IntentClassifier(
        input_size=num_features,
        hidden_size=96,
        num_layers=cfg["num_layers"],
        num_postures=len(POSTURE_CLASSES),
        dropout=cfg["dropout"],
    ).to(cfg["device"])

    print(f"  Parameters: {sum(p.numel() for p in intent_model.parameters()):,}")

    # Setup the same CrossEntropy and Adam optimization framework for Branch B3.
    intent_criterion = nn.CrossEntropyLoss()
    intent_optimizer = optim.Adam(
        intent_model.parameters(), lr=cfg["lr"], weight_decay=cfg["weight_decay"]
    )
    intent_scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        intent_optimizer, mode="min", factor=0.5, patience=3
    )

    # Track best intent performance.
    best_intent_acc = 0.0
    intent_history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": []}

    # Training loop for Branch B3 (Strategy recognition).
    for epoch in range(1, cfg["epochs"] + 1):
        t0 = time.time()
        # Train and validate intent specific data.
        train_loss, train_acc = train_epoch_posture(
            intent_model, train_loader, intent_criterion,
            intent_optimizer, cfg["device"]
        )
        val_loss, val_acc, _, _ = evaluate(
            intent_model, val_loader, intent_criterion, cfg["device"], target_idx=2
        )
        intent_scheduler.step(val_loss)
        dt = time.time() - t0

        # Save metrics for plotting.
        intent_history["train_loss"].append(train_loss)
        intent_history["val_loss"].append(val_loss)
        intent_history["train_acc"].append(train_acc)
        intent_history["val_acc"].append(val_acc)

        # Checkpointing logic for the Intent branch.
        marker = " ★" if val_acc > best_intent_acc else ""
        print(f"  Epoch {epoch:>2}/{cfg['epochs']}  "
              f"Loss: {train_loss:.4f}/{val_loss:.4f}  "
              f"Acc: {train_acc:.3f}/{val_acc:.3f}  "
              f"[{dt:.1f}s]{marker}")

        if val_acc > best_intent_acc:
            best_intent_acc = val_acc
            torch.save(intent_model.state_dict(),
                       os.path.join(cfg["checkpoint_dir"], "intent_classifier_best.pt"))

    # Produce the final strategy-recognition report.
    _, _, p_preds, p_labels = evaluate(
        intent_model, val_loader, intent_criterion, cfg["device"], target_idx=2
    )
    print(f"\n  Best Intent Accuracy: {best_intent_acc:.4f}")
    print("\n  Posture Classification Report:")
    print(classification_report(p_labels, p_preds, target_names=POSTURE_CLASSES,
                                labels=range(len(POSTURE_CLASSES)), zero_division=0))

    # Diagnostic Phase: Save the training/validation curves as PNG for presentation in the interview.
    # ── Save loss curves ──
    _save_loss_curves(action_history, intent_history, cfg["checkpoint_dir"])

    # Persistence Phase: Record the hyperparameters and final scores for future experiment tracking.
    # ── Save training summary ──
    summary = {
        "best_action_accuracy": best_action_acc,
        "best_intent_accuracy": best_intent_acc,
        "epochs": cfg["epochs"],
        "window_size": cfg["window_size"],
        "num_features": num_features,
        "hidden_size": cfg["hidden_size"],
        "device": cfg["device"],
    }
    with open(os.path.join(cfg["checkpoint_dir"], "training_summary.json"), "w") as f:
        json.dump(summary, f, indent=2)

    # Final wrap-up console logs.
    print("\n" + "=" * 55)
    print("  Oracle Training Complete!")
    print(f"  Action predictor:  {best_action_acc:.4f} accuracy")
    print(f"  Intent classifier: {best_intent_acc:.4f} accuracy")
    print(f"  Checkpoints saved: {cfg['checkpoint_dir']}/")
    print("=" * 55)

    # Return the trained models for possible immediate post-processing.
    return action_model, intent_model


# Visualization utility used to generate graphical evidence of model convergence.
def _save_loss_curves(action_hist, intent_hist, output_dir):
    """Generates and saves dual-branch accuracy/loss metrics using Matplotlib."""
    try:
        import matplotlib
        # Configure plotting for environments without a desktop interface (Agg backend).
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        # Create a dashboard-style 2x2 visualization grid.
        fig, axes = plt.subplots(2, 2, figsize=(14, 10))
        fig.suptitle("TDSS Oracle — Training Curves", fontsize=14, fontweight="bold")

        # Visualizing Action branch performance.
        # Action loss (Error rate)
        axes[0, 0].plot(action_hist["train_loss"], label="Train", color="#3498db")
        axes[0, 0].plot(action_hist["val_loss"], label="Val", color="#e74c3c")
        axes[0, 0].set_title("Action Predictor — Loss")
        axes[0, 0].set_xlabel("Epoch")
        axes[0, 0].legend()
        axes[0, 0].grid(True, alpha=0.3)

        # Action accuracy (Success rate)
        axes[0, 1].plot(action_hist["train_acc"], label="Train", color="#3498db")
        axes[0, 1].plot(action_hist["val_acc"], label="Val", color="#e74c3c")
        axes[0, 1].set_title("Action Predictor — Accuracy")
        axes[0, 1].set_xlabel("Epoch")
        axes[0, 1].legend()
        axes[0, 1].grid(True, alpha=0.3)

        # Visualizing Intent branch performance.
        # Intent loss
        axes[1, 0].plot(intent_hist["train_loss"], label="Train", color="#2ecc71")
        axes[1, 0].plot(intent_hist["val_loss"], label="Val", color="#e67e22")
        axes[1, 0].set_title("Intent Classifier — Loss")
        axes[1, 0].set_xlabel("Epoch")
        axes[1, 0].legend()
        axes[1, 0].grid(True, alpha=0.3)

        # Intent accuracy
        axes[1, 1].plot(intent_hist["train_acc"], label="Train", color="#2ecc71")
        axes[1, 1].plot(intent_hist["val_acc"], label="Val", color="#e67e22")
        axes[1, 1].set_title("Intent Classifier — Accuracy")
        axes[1, 1].set_xlabel("Epoch")
        axes[1, 1].legend()
        axes[1, 1].grid(True, alpha=0.3)

        # Tighten the UI layout to prevent overlap.
        plt.tight_layout()
        path = os.path.join(output_dir, "training_curves.png")
        # Save high-resolution graphic to the checkpoint folder.
        plt.savefig(path, dpi=150)
        plt.close()
        print(f"\n  📈 Loss curves saved: {path}")
    except Exception as e:
        # Failure log if libraries are missing or drive is full.
        print(f"\n  ⚠ Could not save loss curves: {e}")


# Python safe-execution block.
if __name__ == "__main__":
    # Start the full engine training process.
    train_oracle()
